### ISSUE TITLE
aoscx_upload_firmware 401 Authorization Required Aruba CX 6200f / 6300M

### ISSUE THREAD

**Issue by mrfischl** [aruba/aoscx-ansible-collection#78] opened 2023-07-08 18:19 UTC
Hey Guys,

I've been using Ansible for a few weeks and have written a playbook for updating Aruba CX switches. Unfortunately, I have problems with the firmware upload on the CX6200F and 6300M.

**The Problem:**
fatal: [aoscx_1]: FAILED! => {"changed": false, "msg": "'GENERIC OPERATION ERROR: 401 Authorization Required: Code: 401'"}

I forgot the "-vvv" but i can post it later if required.

My test-setup:

**Versions:**
Ansible: ansible [core 2.14.6]
Python3: 3.10.6
Aoscx: arubanetworks.aoscx 4.2.1
Ubuntu: 22.04.2 LTS
Aruba CX 6200f: ML.10.10.1040

**Inventory**
all:
  hosts:
    aoscx_1:
      ansible_host: 192.168.178.253
      ansible_user: <username>
      ansible_password: <password>
      ansible_network_os: arubanetworks.aoscx.aoscx
      ansible_connection: arubanetworks.aoscx.aoscx 
      ansible_aoscx_validate_certs: False
      ansible_aoscx_use_proxy: False
      ansible_acx_no_proxy: True

**Playbook**
- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False
  tasks:
    - name: Upload
      aoscx_upload_firmware:
        partition_name: 'primary'
        firmware_file_path: '/root/ansible/firmware/ArubaOS-CX_6200_10_10_1010.swi'

**Switch:**
Current configuration:
!
!Version ArubaOS-CX ML.10.10.1040
!export-password: default
user admin group administrators password ciphertext <password>
ntp server pool.ntp.org minpoll 4 maxpoll 4 iburst
ntp enable
!
ssh server vrf default
ssh server vrf mgmt
vsf member 1
    type jl725a
vlan 1
spanning-tree
interface mgmt
    no shutdown
    ip dhcp
interface 1/1/1-1/1/28
    no shutdown
    no routing
    vlan access 1
interface vlan 1
    ip address 192.168.178.253/24
    ip dhcp
        ! ip dhcp is ignored when static ip is configured
!
!
!
!
!
https-server vrf default
https-server vrf mgmt

https-server rest access-mode read-write \\configured but not displayed in "show run"?!

----------
**Other tests:**

**aoscx_vlan - works fine
Aruba CX 6100 - Firmware upload no problems**

Wireshark - in the pcap i can see that the file transfer is running

Hope you can help me.

Greetings Lukas

**Comment by mrfischl** [comment] 2023-07-11 12:42
1. The switch is running version 10_10_1040.
2. see below
3. After 1 min and a few seconds
4. All requirements are installed

Error:
The full traceback is:
  File "/tmp/ansible_aoscx_upload_firmware_payload_x25so1fj/ansible_aoscx_upload_firmware_pa/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_upload_firmware.py", line 167
  File "/usr/local/lib/python3.10/dist-packages/pyaoscx/device.py", line 565, in upload_firm
    result = self.upload_firmware_local(
  File "/usr/local/lib/python3.10/dist-packages/pyaoscx/device.py", line 518, in upload_firml
    success = utils.file_upload(
  File "/usr/local/lib/python3.10/dist-packages/pyaoscx/utils/util.py", line 309, in file_up
    raise GenericOperationError(
fatal: [aoscx_1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "firmware_file_path": "/root/ansible/firmware/ArubaOS-CX_6200_10_10_1010.swi",
            "partition_name": "primary",
            "remote_firmware_file_path": null,
            "vrf": null,
            "wait_firmware_upload": false
        }
    },
    "msg": "'GENERIC OPERATION ERROR: 401 Authorization Required: Code: 401'"
}

**Comment by mrfischl** [comment] 2023-07-13 05:54
@tchiapuziowong In our productive system is the location /home/user/ansible/firmware/
Same problem.

**Comment by tchiapuziowong** [comment] 2023-07-13 13:46
Can you provide the versions you have installed for the following Python libraries?
```
paramiko
requests
ansible-pylibssh
pyaoscx
pycurl
```

**Comment by JSTBotanic** [comment] 2023-07-13 14:43
Hi @mrfischl 
Can you send me your code for upload firmware for Aruba AOSCX 6100 please ?
I have some errors and i don't understand.

**Comment by mrfischl** [comment] 2023-07-14 06:01
@tchiapuziowong 
`paramiko 3.2.0
requests 2.31.0
ansible-pylibssh 1.1.0
pyaoscx 2.4.1
pycurl 7.45.2`

**Comment by mrfischl** [comment] 2023-07-14 06:31
@JSTBotanic Hi, check out "Getting Started with Ansible and AOS-CX" there is a example. You just need to change the module.
Module example: https://github.com/aruba/aoscx-ansible-role/blob/master/docs/aoscx_upload_firmware.md

**Comment by tchiapuziowong** [comment] 2023-07-19 17:55
Thank you @smirlach  and @mrfischl for the information! I'm working on reproducing the issue in our setup and will bring this up internally - I may be asking for more information so I appreciate your patience and cooperation!

@smirlach can you provide the output of `ansible --version`?

**Comment by tchiapuziowong** [comment] 2023-07-21 20:57
@smirlach @mrfischl I'm unable to reproduce the error you're receiving - the IP address you're connecting to the switch, is that on the management VRF/interface or through the front ports?

**Comment by mrfischl** [comment] 2023-07-24 15:05
@tchiapuziowong 
The Interface-vlan 1 vrf-default is connected to the Front Ports in my test.

**Comment by mrfischl** [comment] 2023-08-14 09:35
@tchiapuziowong 
Can you maybe share a example for a 6200F Switch (ansible.cfg, playbook,, inventory)?
My playbook is still running for a 6100 Switch.

**Comment by tchiapuziowong** [comment] 2023-08-14 19:25
the inventory/playbook would be the same for any model of switch - this may be an issue seen only when using a non-management VRF to connect to the switch

**Comment by mrfischl** [comment] 2023-08-15 19:22
@tchiapuziowong 
THX, I tested it! Too bad it doesn't work with the front ports.
In our case, we used hundreds of switches without mgmt-port.

**Comment by tchiapuziowong** [comment] 2023-08-15 21:59
@mrfischl reopening - our internal team is still investigating why it's failing non-mgmt, I'll update this issue once we have more information regarding the behavior

**Comment by jonathanbaird** [comment] 2023-09-14 18:13
Hi is there any update on this? I have the same problem using a 6100 series switch with the default vrf

**Comment by jonathanbaird** [comment] 2023-09-14 18:16
i am also having this issue with a 6100 series switch. there's no option to use a mgmt vrf in my instance so i am forced to use the default vrf

**Comment by tchiapuziowong** [comment] 2023-09-19 21:06
Hi @jonathanbaird - we're evaluating the fix for an upcoming minor release and will update the issue once it's implemented, thank you for your continued patience during this time. As a workaround you could utilize the SSH module **aoscx_command** to upload a firmware using a server - for a full example see our workflows repository here: https://github.com/aruba/aoscx-ansible-workflows/blob/main/copy_config_using_cli_prompt.yml

**Comment by mrfischl** [comment] 2024-01-16 10:26
@tchiapuziowong Any updates?

**Comment by tchiapuziowong** [comment] 2024-03-01 17:39
We've just published a fix for this issue, please install the latest version of the collection and verify if you no longer see this issue:

```ansible-galaxy collection install arubanetworks.aoscx -f ```

**Comment by tchiapuziowong** [comment] 2024-03-14 19:07
@2relativ if you install the latest version of the collection are you still running into the same issue without explicitly defining `wait_firmware_upload`?

**Comment by 2relativ** [comment] 2024-03-14 19:26
> @2relativ if you install the latest version of the collection are you still running into the same issue without explicitly defining `wait_firmware_upload`?

Yes. Definitely. I tried first a workaround until I saw this option in the debug log. The interesting part is, that the switch itself wouldn't let me in over webinterface also. So, I would definitely set the wait_firmware_upload as default. But please be careful since my upload is over http from a different server. So the ansible server has to explicitly request if the server is ready instead of maybe monitoring the firmware upload from himself.

**Comment by alagoutte** [comment] 2024-03-14 20:01
> Hey, I had the same error message but I was uploading the firmware through http instead of using local resources. What I did different to get around this was using the switch wait_firmware_upload: True which I found while using debug mode. After that Ansible did indeed wait until the upload was done and confirmed instead of just triggern the update and going on. This should maybe also be used in the examples?! Both on github and on the aruba page or wait_firmware_upload should be enabled by default?

i have already open a PR #98 for add missing wait_firmware_upload, I has the same issue when use http/https

**Closed** 2024-07-22 19:24 UTC
