### ISSUE TITLE
aoscx_vlan does not assign VLAN name when using only ID and name 

### ISSUE THREAD

**Issue by br0v** [aruba/aoscx-ansible-collection#13] opened 2021-11-09 14:55 UTC
Hi,

My playbook uses the aoscx_vlan module to create vlans on a 6300M. The vlans should only have a name and an ID. 

Please see my task below:

```yaml
  - name: Create VLAN10
    aoscx_vlan:
      vlan_id: 10
      name: "I am vlan 10"
```
This task executes successfully, but creates a vlan with a default name instead of the name I supplied in my playbook.

To illustrate this, please see this section from the running config after executing the playbook:
```
vlan 10
    name vlan10
```

I found that vlans which contain the name and the description in the playbook will assign the name which is supplied in the playbook. Meaning that this task will work as expected:
```yaml
  - name: Create VLAN15
    aoscx_vlan:
      vlan_id: 15
      name: "I am vlan 15"
      description: "Does this work?"
```
Again an example from the running config:
```
vlan 15
    name I am vlan 15
    description Does this work?
```
It would be nice to be able to get proper vlan names without having to provide a vlan description.

Regards,

b

**Comment by alagoutte** [comment] 2021-11-09 15:03
what your inventory ?

do you have pyaoscx ?

**Comment by br0v** [comment] 2021-11-09 15:07
That was fast :)

Yep, I have pyaoscx version 2.1.0 installed

Followed your guide on the main page to set up the variables for the inventory.

**Comment by alagoutte** [comment] 2021-11-09 15:11
with python 2 or 3 ?

**Comment by br0v** [comment] 2021-11-09 15:12
Python 3

**Comment by alagoutte** [comment] 2021-11-09 15:16
ok, i have try i get the same issue if i don't set description name...
i need to retry without pyaoscx

**Comment by tchiapuziowong** [comment] 2021-11-09 19:25
We're looking into this issue - thank you for bringing it to our attention! I'll update once we've published a fix!

**Comment by tchiapuziowong** [comment] 2021-11-29 21:33
I've uploaded a fix for this issue in the latest version of the collection - please update your collection by using the below command:
`ansible-galaxy collection install arubanetworks.aoscx -f`

**Comment by alagoutte** [comment] 2021-11-30 07:21
Thanks, i will try !

it is not possible to tag the release ?

**Comment by tchiapuziowong** [comment] 2021-11-30 16:22
It's already versioned in galaxy - if you want to install the specific version you can do :
`ansible-galaxy collection install arubanetworks.aoscx:3.0.2 -f`

**Comment by alagoutte** [comment] 2021-11-30 16:52
i talk on GitHub ;)

**Comment by tchiapuziowong** [comment] 2021-11-30 16:53
we haven't been tagging releases on Github just using the galaxy.yml file for versioning - is that something you use in installation?

**Comment by alagoutte** [comment] 2021-11-30 19:11
> we haven't been tagging releases on Github just using the galaxy.yml file for versioning - is that something you use in installation?

Yes for dev, for get/test directly the same version 

(And for the CI, can be nice with Github actions with the change log on release !)

**Comment by tchiapuziowong** [comment] 2021-11-30 19:21
just created a release! 
https://github.com/aruba/aoscx-ansible-collection/releases/tag/v3.0.2

**Comment by alagoutte** [comment] 2021-11-30 20:00
Thanks !

**Comment by alagoutte** [comment] 2021-11-30 21:01
it is work

but we loss the idempotent for Vlans,
we have always changed=1 if you relaunch the command (without change...) when have vlan name and/or description

**Comment by tchiapuziowong** [comment] 2021-12-07 01:04
Thanks @alagoutte we're working on that now! 👏

**Comment by tchiapuziowong** [comment] 2022-02-09 00:44
Hello! This should be resolved in the latest version of the AOS-CX Ansible Collection and PYAOSCX - please install the latest of each with the following commands and validate the issue is no longer seen:
`ansible-galaxy collection install arubanetworks.aoscx -f`
`python3 -m pip install --upgrade --force-reinstall pyaoscx`

**Comment by alagoutte** [comment] 2022-02-09 14:12
> Hello! This should be resolved in the latest version of the AOS-CX Ansible Collection and PYAOSCX - please install the latest of each with the following commands and validate the issue is no longer seen: `ansible-galaxy collection install arubanetworks.aoscx -f` `python3 -m pip install --upgrade --force-reinstall pyaoscx`

No longer issue with 4.0.0 for vlan ! Thanks :)

**Closed** 2022-02-09 16:35 UTC
